extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy: disable
  document-start: disable

ignore: |
  .git/
  .venv/
  **/__pycache__/
  labs/prep_evening/k8s_helm/helm/lab27-web/templates/
