extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy: disable
  document-start: disable

ignore: |
  .git/
  .venv/
  **/__pycache__/
  labs/prep_evening/k8s_helm/helm/lab27-web/templates/
  labs/lesson_36/k8s/ingress/
  labs/lesson_37/k8s/ingress/
  labs/lesson_36/kind/calico-manifests/
  labs/lesson_38/k8s/ingress/