---
- name: Install nginx packages
  become: "{{ role_use_become }}"
  ansible.builtin.package:
    name:
      - nginx
      - curl
      - iproute2
    state: present
  register: nginx_pkg

- name: Ensure log dir exists
  become: "{{ role_use_become }}"
  ansible.builtin.file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy site config
  become: "{{ role_use_become }}"
  ansible.builtin.template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable site
  become: "{{ role_use_become }}"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site_name }}.conf"
    state: link
    force: true
  notify: reload nginx

- name: Disable default site if exists
  become: "{{ role_use_become }}"
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Nginx syntax check
  become: "{{ role_use_become }}"
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false

- name: Ensure nginx service started & enabled
  become: "{{ role_use_become }}"
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
