global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml
  
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'local'
          
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: ["http_2xx"]
    static_configs:
      - targets:
        - http://prometheus:9090/-/healthy
        - http://alertmanager:9093/-/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        
      - source_labels: [__param_target]
        target_label: instance
        
      - target_label: __address__
        replacement: blackbox:9115
          
  - job_name: 'nginx'
    static_configs:
      ##- targets: ['127.0.0.1:9113']
      - targets: ['lab18-nginx-exporter:9113']
        labels:
          instance: 'local'
