---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "jrei/systemd-ubuntu:24.04"
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env:
      container: docker
    published_ports:
      - "8080:80"

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: docker
            ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      roles_path: /home/leprecha/ansible_clean/ansible/roles
      remote_tmp: /tmp
      deprecation_warnings: false
  env:
    ANSIBLE_ROLES_PATH: /home/leprecha/ansible_clean/ansible/roles
    ANSIBLE_VERBOSITY: "2"

verifier:
  name: testinfra

lint: |
  set -e
  ansible-lint -v
