{
 "title": "Labweb Golden Signals",
 "tags": [
  "lab",
  "labweb",
  "golden"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "labweb:http_requests_total_5m", "legendFormat": "RPS" }
   ]
  },
  {
   "title": "Error ratio (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "labweb:http_error_ratio_5m", "legendFormat": "5xx ratio" }
   ]
  },
  {
   "title": "CPU usage (node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "labweb:cpu_usage_ratio_5m * 100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "labweb:http_5xx_rate_5m", "legendFormat": "5xx rps" }
   ]
  },
  {
   "title": "Labweb logs (5xx only)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"labweb\"} | json | status=~\"5..\""
    }
   ]
  }
 ]
}