{
 "title": "Nginx Mini",
 "tags": [
  "lab",
  "nginx"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Nginx requests (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[2m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{status=~\"5..\"}[2m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Nginx logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} | json"
    }
   ]
  }
 ]
}