---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    role_use_become: false
    nginx_site_name: lab16
    nginx_backend_host: backend
    nginx_backend_port: 8081
    access_log_json: /var/log/nginx/access.json
    http_port: 80
    health_path: /health
  roles:
    - role: ../..
