---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    net_name: molecule_net
    proxy_name: instance
    backend_name: backend
    proxy_image: "jrei/systemd-ubuntu:24.04"
    backend_image: "python:3.12-slim"
  tasks:
    - name: Ensure network exists
      community.docker.docker_network:
        name: "{{ net_name }}"
        state: present

    - name: Ensure backend image present
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Run backend container (8081)
      community.docker.docker_container:
        name: "{{ backend_name }}"
        image: "{{ backend_image }}"
        state: started
        restart_policy: unless-stopped
        command: python -m http.server 8081 --bind 0.0.0.0
        networks:
          - name: "{{ net_name }}"
        published_ports:
          - "8081:8081"

    - name: Ensure proxy image present
      community.docker.docker_image:
        name: "{{ proxy_image }}"
        source: pull

    - name: Run systemd-enabled proxy
      community.docker.docker_container:
        name: "{{ proxy_name }}"
        image: "{{ proxy_image }}"
        state: started
        restart_policy: unless-stopped
        privileged: true
        command: "/lib/systemd/systemd"
        cgroupns_mode: host
        tmpfs:
          - /run
          - /run/lock
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        env:
          container: docker
        networks:
          - name: "{{ net_name }}"
        published_ports:
          - "8080:80"
