---
- name: Prepare target for Ansible
  hosts: instance
  gather_facts: false
  tasks:
    - name: Ensure python3 and curl present
      ansible.builtin.raw: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y python3 python3-apt curl
      changed_when: false
