---
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    net_name: molecule_net
  tasks:
    - name: Connect 'instance' to molecule_net
      community.docker.docker_network:
        name: "{{ net_name }}"
        connected:
          - instance
        appends: true
        state: present

    - name: Start backend container (simple http server on 8081)
      community.docker.docker_container:
        name: backend
        image: "python:3.12-slim"
        command: "python -m http.server 8081 --bind 0.0.0.0"
        networks:
          - name: "{{ net_name }}"
        published_ports:
          - "8081:8081"
        restart_policy: unless-stopped
        state: started

