---
- name: Verify
  hosts: instance
  gather_facts: false
  tasks:
    - name: Check health
      uri:
        url: "http://127.0.0.1/health"
        method: GET
        status_code: 200
      register: hc

    - name: Assert body contains OK
      assert:
        that:
          - "'OK' in hc.content"

