---
- name: Check health
  hosts: all
  gather_facts: false
  tasks:
    - name: Health endpoint returns 200
      ansible.builtin.uri:
        url: "http://127.0.0.1/health"
        method: HEAD
        status_code: 200
        return_content: false
