name: CI
on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -V
      - run: echo "CI alive"
